[build]
  base = "./"
  command = "npm run build" 
  publish = "./src"
  functions = "./functions_build/"

[dev] 
  publish = "./src" 
  functionsPort = 23456
# port = 9000
# build netlify functions: npm run build

# command = "python -m SimpleHTTPServer 9000"
# find apps using port 8080: sudo lsof -i:8080
# kill those apps: kill <process ID>