[build]
  base = "./"
  command = "npm run build" 
  publish = "./build"
  functions = "./functions-build/"

[dev] 
  # command = "npm run build && python -m SimpleHTTPServer 8080" # unfortunately doesn't work
  # command = "npm run build"
  
  # build netlify functions: npm run build
  publish = "./build" # Folder with the static content for _redirect file
  functionsPort = 23456
#  port = 9000

# command = "python -m SimpleHTTPServer 9000"
# find apps using port 8080: sudo lsof -i:8080
# kill those apps: kill <process ID>